version: '3.8'

services:
  app:
    build: .
    ports:
      - '8081:8081'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn start

volumes:
  node_modules:
